
---
- name: Run playbook
  hosts: all
  become: yes

  roles:
    - role: jdauphant.nginx
    - role: ansible_jenkins_config
  vars:
    nginx_sites:
      default:
        - listen 80
        - "{{ jenkins_nginx_usercontent }}"
        - "{{ jenkins_nginx_root }}"
    jenkins_plugins:
      - ansible
      - ec2
      - github
      - github-oauth
      - simple-theme-plugin
      - slack
      - ssh-credentials
      - workflow-aggregator
