---
- name: Install additional package on jenkins master
  package:
    name: "{{ item }}"
  with_items: "{{ jenkins_master_pkgs }}"

- import_tasks: tweaks.yml
  tags: xml

- import_tasks: config.yml
  tags: config

- import_tasks: plugins.yml
