---
- name: Install additional package on jenkins master
  package:
    name: "{{ item }}"
  with_items: "{{ jenkins_master_pkgs }}"

- import_tasks: tweaks.yml

- import_tasks: config.yml

- import_tasks: plugins.yml
